name: bvt-clang20

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false

jobs:
  bvt-clang20:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: install clang 20
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 20
        sudo apt install libc++-20-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/clang-20 20
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/clang++-20 20

    - name: check compiler version
      run: g++ --version

    - name: build with cmake
      run: |
        cmake . -B build
        cmake --build ./build -j8

    - name: run tests
      run: |
        cd ./build
        ctest -j8
