name: bvt-gcc14

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: false

jobs:
  bvt-gcc14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: install gcc 14
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
        sudo apt update
        sudo apt install -y gcc-14 g++-14
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 14
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 14

    - name: check compiler version
      run: g++ --version

    - name: build with cmake
      run: |
        cmake . -B build
        cmake --build ./build -j8

    - name: run tests
      run: |
        cd ./build
        ctest -j8
